apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  ports:
    - port: 3306
  selector: # Busca todos os pods com essa definição de seletor
    app: mysql-server
    tier: db
  clusterIP: None # define que o serviço do banco de dados não seja acessado fora do cluster